version: '3.2'
services:
    reverse:
        image: nginx:latest
        volumes:
          - ./src/msgde:/var/www/msgde
          - ./src/tadpba-backend:/var/www/php
          - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
          - php
        working_dir: /var/www
        environment:
          - VIRTUAL_HOST=backend.tadpba.lab.mp.gba.gob.ar, msgde.tadpba.lab.mp.gba.gob.ar

    php:
        build: ./php/
        restart: always
        working_dir: /var/www/php
        volumes:
          - ./src/tadpba-backend:/var/www/php
          - ./php/php.ini-development:/usr/local/etc/php/php.ini
        depends_on:
          - mysql

    msgde:
        build: ./php/
        working_dir: /var/www/msgde
        volumes:
          - ./src/msgde:/var/www/msgde
          - ./php/php.ini-development:/usr/local/etc/php/php.ini
        depends_on:
          - mysql

    myadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - VIRTUAL_HOST=myadmin.tadpba.lab.mp.gba.gob.ar
        restart: always
        depends_on:
            - mysql
    mysql:
        image: mysql:${MYSQL_VERSION}
        restart: always 
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - 8306:3306
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
            - "./etc/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf"
    c9:
        build: ./c9/
        volumes:
          - ./src:/workspace
        environment:
          - C9_EXTRA=--auth dev:Motorola2019
          - VIRTUAL_HOST=c9.tadpba.lab.mp.gba.gob.ar

    angular:
        build: ./src/tadpba-frontend/
        command: "npm start"
        expose:
           - 4200
        volumes:
           - "./src/tadpba-frontend:/usr/src/app"
        environment:
           - VIRTUAL_HOST=tadpba.lab.mp.gba.gob.ar
           - VIRTUAL_PORT=4200

networks:
  default:
    ipam:
      config:
        - subnet: ${NETWORK}/24
